# docker-compose.yml

networks:
  domjudge:
    name: DOMJudge

services:
  mariadb:
    container_name: domjudge-mariadb
    image: mariadb:latest
    networks:
      - domjudge
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=djpw
      - MYSQL_DATABASE=domjudge
    command: --max-connections=1000

  domserver:
    container_name: domjudge-domserver
    image: domjudge/domserver:latest
    networks:
      - domjudge
    ports:
      - 12345:80
    depends_on:
      - mariadb
    environment:
      - CONTAINER_TIMEZONE=Asia/Jakarta
      - MYSQL_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=djpw
      - MYSQL_DATABASE=domjudge

  judgehost-0:
    container_name: domjudge-judgehost-0
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-0
    networks:
      - domjudge
    depends_on:
      - domserver
    environment:
      - DAEMON_ID=0
      - JUDGEDAEMON_PASSWORD=${API_PASSWORD}
      
  judgehost-1:
    container_name: domjudge-judgehost-1
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-1
    networks:
      - domjudge
    depends_on:
      - domserver
    environment:
      - DAEMON_ID=1
      - JUDGEDAEMON_PASSWORD=${API_PASSWORD}

  judgehost-2:
    container_name: domjudge-judgehost-2
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-2
    networks:
      - domjudge
    depends_on:
      - domserver
    environment:
      - DAEMON_ID=2
      - JUDGEDAEMON_PASSWORD=${API_PASSWORD}